[package]
name = "bevycraft"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
wasm-bindgen = "0.2.99"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
bevy_mod_picking="0.20.0"

[lib]
crate-type = ["cdylib", "rlib"]